customer/urls.py
from django.urls import path
from . import views
from .views import ProductView,ProductDetailView,CartView,OrderDetailView
urlpatterns = [
    path('',views.home_page, name="home"),
    path('working/',views.working,name="working"),
    path('register/',views.registration_view,name="register"),
    path('logout/',views.logout_view,name="logout"),
    path('login/',views.login_view,name="log-in"),
    path('accounts/login/',views.login_view,name="log-in"),
    path('profile/',views.profile_view,name='profile'),
    path('update-profile/',views.update_profile,name="update-profile"),
    path('product/',ProductView.as_view(),name="product"),
    path('product/<slug:slug>/',ProductDetailView.as_view(),name="product-detail"),
    path('cart/',views.CartView,name="cart"),
    path('add-to-cart/<slug:slug>/',views.add_to_cart,name='add-to-cart'),
    path('remove-from-cart/<slug:slug>/',views.remove_from_cart,name='remove-from-cart'),
    path('remove-single-item-from-cart/<slug:slug>/',views.remove_single_item_from_cart,name='remove-single-from-cart'),
    path('checkout/',views.CheckoutView,name='checkout'),
    path('order/',OrderDetailView.as_view(),name='order-detail-view')
    #path('profile/update-profile/',views.update_profile,name="update_profile"),
]

falling_fruits/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('customer.urls','customer'),namespace='customer')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate

from customer.models import Account,Profile,Address

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Add a valid email address.')

    class Meta:
        model = Account
        fields = ('email', 'username', 'password1', 'password2', )


class AccountAuthenticationForm(forms.ModelForm):

	password = forms.CharField(label='Password', widget=forms.PasswordInput)

	class Meta:
		model = Account
		fields = ('email', 'password')

	def clean(self):
		if self.is_valid():
			email = self.cleaned_data['email']
			password = self.cleaned_data['password']
			if not authenticate(email=email, password=password):
				raise forms.ValidationError("Invalid login")


class AccountUpdateForm(forms.ModelForm):

	class Meta:
		model = Account
		fields = ('email', 'username', )

	def clean_email(self):
		email = self.cleaned_data['email']
		try:
			account = Account.objects.exclude(pk=self.instance.pk).get(email=email)
		except Account.DoesNotExist:
			return email
		raise forms.ValidationError('Email "%s" is already in use.' % account)

	def clean_username(self):
		username = self.cleaned_data['username']
		try:
			account = Account.objects.exclude(pk=self.instance.pk).get(username=username)
		except Account.DoesNotExist:
			return username
		raise forms.ValidationError('Username "%s" is already in use.' % username)

class UserUpdateForm(forms.ModelForm):
	email = forms.EmailField()
	class Meta:
		model = Account
		fields = ['username', 'email']



class ProfileUpdateForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['image','first_name','last_name','contact']

class AddressForm(forms.ModelForm):
	class Meta:
		model= Address
		fields= ['name','street_address','village_name','pincode','contact_number','delivery_time_slot']

customer/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.urls import reverse
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from customer.forms import RegistrationForm, AccountAuthenticationForm,UserUpdateForm,ProfileUpdateForm,AddressForm
from django.contrib import messages
from .models import Product,OrderItem,Order,Address
from django.views.generic import ListView, DetailView
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin
def home_page(request):
	return render(request,'customer/home.html')

def working(request):
    return render(request,'customer/working-model.html')
def registration_view(request):
	context = {}
	if request.POST:
		form = RegistrationForm(request.POST)
		if form.is_valid():
			form.save()
			email = form.cleaned_data.get('email')
			raw_password = form.cleaned_data.get('password1')
			return render(request,'customer/register-success.html')
		else:
			context['registration_form'] = form

	else:
		form = RegistrationForm()
		context['registration_form'] = form
	return render(request, 'customer/register.html', context)


def logout_view(request):
	logout(request)
	return redirect('customer:home')


def login_view(request):

	context = {}

	user = request.user
	if user.is_authenticated:
		return redirect("customer:home")

	if request.POST:
		form = AccountAuthenticationForm(request.POST)
		if form.is_valid():
			email = request.POST['email']
			password = request.POST['password']
			user = authenticate(email=email, password=password)

			if user:
				login(request, user)
				return redirect("customer:home")

	else:
		form = AccountAuthenticationForm()

	context['login_form'] = form

	# print(form)
	return render(request, "customer/login.html", context)




def must_authenticate_view(request):
	return render(request, 'account/must_authenticate.html', {})

@login_required
def profile_view(request):
	context={}
	context['email']=request.user.email
	context['username']= request.user.username
	context['f_name']=request.user.profile.first_name
	context['l_name']=request.user.profile.last_name
	context['contact']=request.user.profile.contact
	context['image']=request.user.profile.image
	return render(request,"customer/profile.html",context)

@login_required
def update_profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('customer:profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'customer/update-profile.html', context)

@login_required
def CartView(request):
    context={}
    order_qs=Order.objects.filter(user=request.user,ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if (order.items.exists()):
            context['orders']=order
            print(order.items)
    print(context)
    return render(request,'customer/cart.html',context)

@login_required
def CheckoutView(request):
    context={}
    order_qs=Order.objects.filter(user=request.user,ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        context['orders']=order
        if request.POST:
            form=AddressForm(request.POST)
            if form.is_valid():
                c_name = form.cleaned_data.get('name')
                street_addr=form.cleaned_data.get('street_address')
                village=form.cleaned_data.get('village_name')
                pin_code=form.cleaned_data.get('pincode')
                contact=form.cleaned_data.get('contact_number')
                default_addr=form.cleaned_data.get('default')
                address_obj=Address(
                    user=request.user,
                    name=c_name,
                    street_address=street_addr,
                    village_name=village,
                    contact_number=contact,
                    pincode=pin_code,
                    default=default_addr
                    )
                address_obj.save()
                Order.objects.filter(user=request.user,ordered=False).update(address=address_obj)
                order_items = order.items.all()
                order_items.update(ordered=True)
                for item in order_items:
                    item.save()
                Order.objects.filter(user=request.user,ordered=False).update(ordered=True)                
                return redirect('customer:order-detail-view',)
        else:
            form=AddressForm()
        context['form']=form
    else:
        context={}
    
    return render(request,'customer/checkout.html',context)

class OrderDetailView(ListView):
    template_name='customer/order-detail.html'
    context_object_name = 'orders'
    model=Order
    def get_queryset(self):
        return Order.objects.filter(user=self.request.user,ordered=True)
    
class ProductView(ListView):
	template_name='customer/product-list.html'
	context_object_name = 'product'
	paginate_by = 12
	model=Product
   

class ProductDetailView(DetailView):
	model = Product
	template_name='customer/product-detail.html'
	context_object_name = 'product'
	def get_object(self, **kwargs):
		return Product.objects.get(slug=self.kwargs['slug'])

@login_required
def add_to_cart(request, slug):
    item = get_object_or_404(Product, slug=slug)
    order_item, created = OrderItem.objects.get_or_create(
        product=item,
        user=request.user,
        ordered=False
    )
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.items.filter(product__slug=item.slug).exists():
            order_item.quantity += 1
            order_item.save()
            #messages.info(request, "This item quantity was updated.")
            return redirect("customer:cart")
        else:
            order.items.add(order_item)
            messages.info(request, "This item was added to your cart.")
            return redirect("customer:product")
    else:
        ordered_date = timezone.now()
        order = Order.objects.create(
            user=request.user, ordered_date=ordered_date)
        order.items.add(order_item)
        messages.info(request, "This item was added to your cart.")
        return redirect("customer:product")

@login_required
def remove_from_cart(request, slug):
    item = get_object_or_404(Product, slug=slug)
    order_qs = Order.objects.filter(
        user=request.user,
        ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.items.filter(product__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(
                product=item,
                user=request.user,
                ordered=False
            )[0]
            order.items.remove(order_item)
            order_item.delete()
            #messages.info(request, "This item was removed from your cart.")
            return redirect("customer:cart")
        else:
            #messages.info(request, "This item was not in your cart")
            return redirect("customer:cart")
    else:
        messages.info(request, "You do not have an active order")
        return redirect("customer:cart")

@login_required
def remove_single_item_from_cart(request, slug):
    item = get_object_or_404(Product, slug=slug)
    order_qs = Order.objects.filter(
        user=request.user,
        ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.items.filter(product__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(
                product=item,
                user=request.user,
                ordered=False
            )[0]
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
            else:
                order.items.remove(order_item)
            messages.info(request, "This item quantity was updated.")
            return redirect("customer:cart")
        else:
            messages.info(request, "This item was not in your cart")
            return redirect("customer:cart", slug=slug)
    else:
        messages.info(request, "You do not have an active order")
        return redirect("customer:cart", slug=slug)

customer/templates/customer/base.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>Falling Fruits</title>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.1/css/all.css" integrity="sha384-xxzQGERXS00kBmZW/6qxqJPyxW3UR0BPsL4c8ILaIWXva5kFi7TxkIIaMiKtqV1Q" crossorigin="anonymous">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <style media="screen">
    .username:hover{
      color:green;
    }
  </style>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light" style="font-size:130%;">
    <a class="navbar-brand " href="{% url 'customer:home' %}"><img class="rounded-circle" width="100px" height="65px" src="https://i.ibb.co/6sr26Q2/f12f2a11-f31c-483e-a875-9fd29614876b-200x200.png" alt="logo-size-invert" border="0"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'customer:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'customer:working' %}">How We Work? </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'customer:product' %}">Products </a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item dropdown active">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Account
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{%url 'customer:profile'%}">Profile</a>
                    <a class="dropdown-item" href="{%url 'customer:order-detail-view'%}">Orders</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Sell Items</a>
                </div>

                {%endif%}
            </li>

        </ul>
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
        <li class="nav-item active ">
              <a class="nav-link" href="{% url 'customer:cart' %}">Cart <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active ">
          <p class="username"style="font-size:117%;">Hello {{user.username}}</p>
        </li>
        <li class="nav-item active ">
          <a class="nav-link" href="{% url 'customer:logout'%}">Logout <span class="sr-only">(current)</span></a>
        </li>

        {%else%}
        <li class="nav-item active ">
          <a class="nav-link" href="{% url 'customer:log-in' %}">Sign In <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'customer:register'%}">Register <span class="sr-only">(current)</span></a>
        </li>
        {%endif%}
      </ul>
    </div>
  </nav>
  {% block content %}
  {% endblock %}
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>

</html>

customer/templates/customer/cart.html
{%extends 'customer/base.html'%}
{%load cust_filters%}
{%block content%}
    <style>


        body {
            background-color: mintcream;
        }
    </style>
    <div class="container">
        {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible" style="text-align:center" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
        </div>
        {% endfor %}

        {% if orders %}
        <table class="table">
            <thead class="thead-light">
                <tr>
                    <th scope="col">Item</th>
                    <th scope="col">Quantity&nbsp;(Kg)</th>
                    <th scope="col">Price&nbsp;(Per Kg)</th>
                    <th scope="col">Total</th>
                </tr>
            </thead>
            <tbody>

                {% for item in orders.items.all%}
                <tr>
                    <td>{{ item.product.category|get_item_name}}</td>
                    <td>{{item.quantity}}&nbsp;&nbsp;<span><a href="{%url 'customer:add-to-cart' item.product.slug%}"><i class="fas fa-plus-circle"></a></i>&nbsp;&nbsp;<a href="{%url 'customer:remove-single-from-cart' item.product.slug%}"><i class="fas fa-minus-circle"></a></i>&nbsp;&nbsp;<a href="{% url 'customer:remove-from-cart' item.product.slug%}"><i class="fas fa-trash"></i></a></span></td>
                    <td>{{item.product.price}}</td>
                    <td>{{item.get_total_item_price}}</td>
                </tr>
                {%endfor%}
                <br>
                <tr>
                    <td></td>
                    <td></td>
                    <td>Order Total</td>

                    <td>{{orders.get_total}}</td>
                </tr>
            </tbody>
        </table>
        <a  href="{%url 'customer:product'%}" type="button" class="btn btn-success">Explore More Products</a>
        <a href="{%url 'customer:checkout'%}" type="button" class="btn btn-success float-right">Proceed to Checkout</a>
        
        {%else%}
        <div class="alert alert-secondary" style="text-align:center;" role="alert">
            You do not have any product in your cart
            <a href="{% url 'customer:product'%}" type="button" class="btn btn-success">Explore Products</a>
        </div>

        {%endif%}



    </div>
    
{%endblock content%}

customer/templates/customer/checkout.html
{%extends 'customer/base.html'%}
{%load crispy_forms_tags%}
{%load cust_filters%}
{%block content%}
<style>


    body {
        background-color: mintcream;
    }
</style>
<div class="container-fluid">
    <div class="row mt-2">
        <div class="col-md-6 border border-light" style="background-color:aliceblue;">
            <h3 style="text-align:center;margin-bottom:15px;">Your cart</h3>
            <table class="table">
                <thead class="thead-light">
                    <tr>
                        <th scope="col">Item</th>
                        <th scope="col">Quantity&nbsp;(Kg)</th>
                        <th scope="col">Price&nbsp;(Per Kg)</th>
                        <th scope="col">Total</th>
                    </tr>
                </thead>
                {% if orders%}
                <tbody>
                    {% for item in orders.items.all%}

                    <tr>
                        <td>{{ item.product.category|get_item_name}}</td>
                        <td>{{item.quantity}}</td>
                        <td>{{item.product.price}}</td>
                        <td>{{item.get_total_item_price}}</td>
                    </tr>




                    {%endfor%}
                </tbody>

            </table>
            <table class="float-right mr-5">
                <tr>
                    <td style="font-size:120%;"><strong>Order Total</strong>&nbsp;</td>

                    <td><button class="btn btn-success">{{orders.get_total}}</button></td>

                </tr>
            </table>
            {%else%}
            <div class="alert alert-secondary" style="text-align:center;" role="alert">
                Your cart is empty.

            </div>
            {%endif%}


        </div>
        <div class="col-sm-6 col-md-6  border border-light ">
            <h3 style="text-align:center;margin-bottom:1px;">Your Address</h3>
            <form class="" action="" method="post">
                {% csrf_token %}
                {{form|crispy}}
                <button class="btn btn-success" type="submit" name="button">Checkout</button>
            </form>
        </div>
    </div>
</div>

{%endblock content%}

customer/templates/customer/home.html
{% extends "customer/base.html" %}
{%load cust_filters%}
{% load static %}
{% block content %}
<style>
    .navbar {
        margin-bottom: -40px;
        margin-top: -25px;
        border-radius: 0;
    } 
    .product{
        margin-top:40px;
    }
    body{
        background-color:mintcream;
    }
</style>
<div class="container product">
    {% for products in product%}
    {% if forloop.counter0|divisibleby:4 %} <div class="row text-center">
        {%  endif %}
        <div class="col-md-3 mb-4 mb-md-0 listproduct" style="cursor: pointer">
            <div class="card">
                <img  width="100%" height="200px"src="{%static 'customer/'%}{{products.category|splitcat}}" alt="Not available">
                <div class="card-content" style="background-color:aliceblue;">
                    <br>
                    <h4>{{products.category}}</h4>
                    <hr>
                    <h3>{{ products.price }}&nbsp; &#8377; &bsol; kg</h3>
                    <button class="btn btn-primary mb-2">{{ products.farm.farm_name }}</button>
                    <button class="btn btn-success mb-2">Add to Cart</button>
                    <br>

                </div><!-- card content -->
            </div><!-- card -->
        </div><!-- col-md-4 -->
        {%  if forloop.counter|divisibleby:4 or forloop.last %}
    </div><!-- row closing --><hr>
    {%  endif %}
    {%  endfor %}
</div><!-- container -->
<div class="jumbotron" style="margin-bottom:0px;">
    <h1 class="display-4">Welcome to Falling Fruits</h1>
    <p class="lead">A Place where you can buy and sell fresh fruits</p>
    <p class="lead">Our Motive is to Dwindle the distance between buyer and seller.</p>

</div>
<div class="jumbotron" style="background-color:green;color:white;margin-bottom:0px;">
    <h1 class="display-4">How we work?</h1>
    <p class="lead">We directly connects you with the producer/consumer without any involvement of Middlemen</p>
</div>
<div class="jumbotron" style="background-color:purple;color:white">
    <h1 class="display-4">What you can sell/buy?</h1>
    <ul class="list-group mt-4" style="text-align:center;font-size:120%">
        <li class="list-group-item list-group-item-primary">Fresh Fruits & Vegetables</li>
        <li class="list-group-item list-group-item-secondary">Grains</li>
        <li class="list-group-item list-group-item-success">Spices</li>
        <li class="list-group-item list-group-item-danger">Cotton</li>
    </ul>
    <p style="color:grey;text-align:center">*Availability of these items is based on Season(Spring,Winter or Summer)</p>
</div>
{% endblock content%}

customer/templates/customer/login.html
{%extends "customer/base.html"%}
{%block content%}
{% load crispy_forms_tags %}

<div class="" >
  <div class="jumbotron">


  <form class="" action="" method="post">
    {% csrf_token %}
        {{ login_form|crispy }}
    <button class="btn btn-success"type="submit" name="button">Submit</button>
  </form>
  </div>
  </div>
{%endblock content%}

customer/templates/customer/product-detail.html
{% extends "customer/base.html" %}
{%load cust_filters%}
{% load static %}
{% block content %}
    <style>
        .d-flex{
            background-color:aliceblue;
        }
    </style>
    <div class="d-flex justify-content-center align-items-center">
        <div class="card" style="width: 18rem;">
            <img class="card-img-top" width="100%" height="250px;"src="{%static 'customer/'%}{{product.category|splitcat}}" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">{{product.category}}</h5>
                <a href="#" class="btn btn-primary mb-2">{{product.farm.farm_name }}</a>
                <a href="{% url 'customer:add-to-cart' product.slug%}" class="btn btn-primary mb-2">Add to Cart</a>
                <a href="{% url 'customer:remove-from-cart' product.slug%}" class="btn btn-primary mb-2">Remove From Cart</a>
            </div>
            <p style="text-align:center">
                Item sold by <a href="#">{{product.farm.farm_name }}</a></p>
        </div>
    </div>
{% endblock content%}

customer/templates/customer/product-list.html
{% extends "customer/base.html" %}
{%load cust_filters%}
 {% load bootstrap_pagination %}
{% load static %}
{% block content %}
{%load crispy_forms_tags%}
<style>


    body {
        background-color: mintcream;
    }
</style>


<div class="container">
    {% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible" style="text-align:center" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        {{ message }}
    </div>
    {% endfor %}
    {% for products in product%}
    {% if forloop.counter0|divisibleby:4 %}
    <div class="row text-center">
        {%  endif %}
        <div class="col-sm-6 col-md-3  mb-4 mb-md-0" style="cursor: pointer">
            <a href="{% url 'customer:product-detail' products.slug%}" style="text-decoration:none;">
                <div class="card">
                    <img width="100%" height="230px" src="{%static 'customer/'%}{{products.category|splitcat}}" alt="Not available">
            </a>
            <div class="card-content" style="background-color:aliceblue;">
                <br>
                <h4>{{products.category}}</h4>
                <hr>
                <h3>{{ products.price }}&nbsp; &#8377; &#47; kg</h3>

                <button class="btn btn-primary mb-2">{{ products.farm.farm_name }}</button>
                <a href="{% url 'customer:add-to-cart' products.slug%}"><button class="btn btn-success mb-2">Add to Cart</button></a>
                <br>

            </div><!-- card content -->
        </div><!-- card -->

    </div><!-- col-md-4 -->
    {%  if forloop.counter|divisibleby:4 or forloop.last %}
</div><!-- row closing -->
<hr>{%  endif %}
    {%  endfor %}



</div><!-- container -->
<div class="d-flex justify-content-center align-items-center">
    {% bootstrap_paginate page_obj range=10 show_prev_next="false" show_first_last="true" %}
</div>
{% endblock content%}

customer/templates/customer/profile.html
{% extends 'customer/base.html'%}
{%block content%}
<style>
    .profile-field {
        font-size: 130%;
    }

    .jumbotron {
        background-color: darkgray;
    }
    .profile-section{
        background-color:green;
        color:white;
    }
</style>
{% if messages %}
    {% for message in messages %}
<div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}" role="alert">{{ message }}</div>
    {% endfor %}
{% endif %}
<div class="main">
    <div class="jumbotron">
        <div class="  ml-4 mr-4 py-2 inside">
            <div class="row text-center">
                <div class="col-12">
                    <img width="80px" height="80px" src="{{user.profile.image.url}}" class="rounded-circle" style="margin: 0 auto;" />
                    <h1 style="color:green;">{{username}}</h1>
                    <div class="profile-section pb-4">
                        <p>Profile Info</p>
                        Name<p class="profile-field"><strong>{{f_name}}&nbsp;{{l_name}}</strong></p>

                        Contact<p class="profile-field">{{contact}}</p>
                        Email<p class="profile-field">{{email}}</p>
                        <a href="{% url 'customer:update-profile' %}"><button class="btn btn-primary">Update Profile</button></a>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

{%endblock content%}

customer/templates/customer/register-success.html
{%extends 'customer/base.html'%}
{% block content %}
<div class="jumbotron">
  <h1>Registration Successfull.Now you can Sign In.</h1>
  <a href="{% url 'customer:log-in'%}"><button class="btn btn-success"type="button" name="button">Sign In</button></a>
</div>
{%endblock content%}

customer/templates/customer/register.html
{%extends "customer/base.html"%}
{%block content%}
{% load crispy_forms_tags %}

<div class="jumbotron" >
  <form class="" action="" method="post">
    {% csrf_token %}
        {{ registration_form|crispy }}
    <button class="btn btn-success"type="submit" name="button">Submit</button>
  </form>
  </div>
{%endblock content%}

customer/templates/customer/update-profile.html
{% extends "customer/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="jumbotron">
        <div class="row text-center">
            <div class="col-12">
                <img width="80px" height="80px" src="{{user.profile.image.url}}" class="rounded-circle" style="margin: 0 auto;" />
             </div>
        </div>
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Profile Info</legend>
                        {{ u_form|crispy }}
                        {{ p_form|crispy }}
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-outline-info" type="submit">Update</button>
                    </div>
                </form>
            </div>
{% endblock content %}